---
- hosts: [home]
  become: true
  become_method: sudo
  tasks:
   - name: make sqldump
     shell: mysqldump test > /tmp/test.sql
   - name: copy dump to local
     fetch:
      src: /tmp/test.sql
      dest: /home/dirty_man/backup
